version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    volumes:
      - c:\es\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - c:\es\book_backup\agg_example:/usr/share/elasticsearch/agg_example
    environment:
      - cluster.name=javacafe-cluster
      - bootstrap.memory_lock=true
      - node.name=javacafe-node1
      - path.repo=/usr/share/elasticsearch/agg_example
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    ports:
      - "5601:5601"